# Generated by Django 4.1.1 on 2022-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100)),
                ('PRDDescription', models.TextField()),
                ('PRDPric', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PRDCost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('PRDcreated', models.DateTimeField()),
            ],
        ),
    ]
