# Generated by Django 4.1.1 on 2022-10-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sup category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.category', verbose_name='Main category'),
        ),
        migrations.CreateModel(
            name='product_alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLANAlternative', models.ManyToManyField(related_name='alternatives', to='products_app.product')),
                ('PLANProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='products_app.product')),
            ],
            options={
                'verbose_name': 'product alternatives',
                'verbose_name_plural': 'product alternative',
            },
        ),
    ]
