# Generated by Django 4.1.1 on 2022-10-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_product_prdcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDACCAlternative', models.ManyToManyField(related_name='accessories_alternatives', to='products_app.product')),
                ('PRDACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_product', to='products_app.product')),
            ],
            options={
                'verbose_name': 'product accessory',
                'verbose_name_plural': 'product accessories',
            },
        ),
    ]
