# Generated by Django 4.1.1 on 2022-10-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_product_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_accessory',
            name='PRDACCAlternative',
            field=models.ManyToManyField(related_name='accessories_alternatives', to='products_app.product', verbose_name='product accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessory',
            name='PRDACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_product', to='products_app.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PLANAlternative',
            field=models.ManyToManyField(related_name='alternatives', to='products_app.product', verbose_name='product alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PLANProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='products_app.product', verbose_name='product'),
        ),
    ]
