# Generated by Django 4.1.1 on 2022-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_product_prdbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='product image'),
        ),
    ]
