# Generated by Django 4.1.1 on 2022-10-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ADPric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='product pric'),
        ),
    ]
