# Generated by Django 4.1.1 on 2022-10-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_product_adpric'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_accessory',
            name='PRDACCAlternativeimage',
            field=models.ImageField(default=2, upload_to='product_photo', verbose_name='product image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ADPric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='product pric after discount'),
        ),
    ]
