# Generated by Django 4.1.1 on 2022-10-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0011_product_accessory_prdaccalternativeimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_accessory',
            name='PRDACCAlternativeimage',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='product image'),
        ),
    ]
