# Generated by Django 4.1.1 on 2022-10-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0015_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDnew',
            field=models.BooleanField(default=True),
        ),
    ]
