# Generated by Django 4.1.1 on 2022-10-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRDname', models.CharField(max_length=50, verbose_name='brand name')),
                ('BRDdescription', models.TextField(blank=True, max_length=1000, null=True, verbose_name='brand description')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARname', models.CharField(max_length=50, verbose_name='variant name')),
                ('VARdescription', models.TextField(blank=True, max_length=1000, null=True, verbose_name='variant description')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
            },
        ),
    ]
